//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemandeMission.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MISSION
    {
        public decimal ID { get; set; }
        public string NOM { get; set; }
        public string PRÉNOM { get; set; }
        public decimal N__PASSEPORT { get; set; }
        public string NATIONALITÉ { get; set; }
        public string FONCTION { get; set; }
        public string TITRE_EQUIPE { get; set; }
        public string MOTIF_DE_MISSION { get; set; }
        public string INTITULÉ_DE_MISSION { get; set; }
        public System.DateTime DATE__DÉPART { get; set; }
        public System.DateTime DATE_RETOUR { get; set; }
        public string OBJET_DE_MISSION { get; set; }
        public decimal TELEPHONE { get; set; }
        public string EMAIL { get; set; }
        public string STATUS { get; set; }
    }
}
